name: Daily Test

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        dotnet-version: [ '8.*' ]
        
    steps:
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.*'
      
    - name: Restore dependencies
      run: dotnet restore RadiantConnect.csproj

    - name: Build the project
      run: dotnet build RadiantConnect.csproj --configuration Release --framework net8.0
      
    - name: Test RadiantConnect.Tests
      run: dotnet test RadiantConnect.Tests/RadiantConnect.Tests.csproj --no-restore --verbosity normal
