name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        dotnet-version: [ '8.*' ]
        
    steps:
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.*'

    - name: Get Structure
      run: ls
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --framework net8.0

    - name: Publish the project
      run: dotnet publish --configuration Release --framework net8.0 --output ./bin/Release/net8.0/publish

    - name: Archive published files
      uses: actions/upload-artifact@v4
      with:
        name: published-files
        path: ./bin/Release/net8.0/publish/
